image: python:3.7-alpine

stages:
  - tests
  - deploy

before_script:
  - pip install twine pipenv pytest
  - pipenv install --dev

run_tests:
  stage: tests
  script:
    - pytest -v -s --disable-warnings

deploy:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - python setup.py sdist
    - twine upload --skip-existing dist/*
  only:
    - production