image: python:3.7-alpine

stages:
  - tests
  - deploy

before_script:
  - pip install twine pipenv
  - pipenv run pip freeze > requirements.txt
  - pip install -r requirements.txt

run_tests:
  stage: tests
  script:
    - echo requirements.txt

deploy:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - python setup.py sdist
    - twine upload --skip-existing dist/*
  only:
    - production